buildings/urls.py
from django.contrib import admin
from django.urls import path

from buildings import views

app_name = 'buildings'

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('list', views.bldg_list, name='bldg_list'),
    path('detail/<int:id>/', views.bldg_detail, name='bldg_detail'),
    path('', views.maplist, name='maplist'),
]

web_config/urls.py
from django.urls import path, include

"""web_config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from buildings import views as bldgviews

urlpatterns = [
    path('', bldgviews.home, name="home"),
    path('admin/', admin.site.urls),
    path('mountains/', include('mountains.urls')),
    path('buildings/', include('buildings.urls')),
]

buildings/models.py
from django.db import models

# Create your models here.

buildings/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
import pymysql.cursors
import folium
from django.http.response import JsonResponse

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='1234',
                             db='mydb',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)


# Create your views here.
def get_weather_skyscrapers(id, results_weather):
    for result in results_weather:
        if id == result['bldg_id']:
            return result
    
    result = list()
    return result
    

def skyscrapers_home(request):
    page = request.GET.get('page', '1')

    with connection.cursor() as cursor:
        # 지도에 마커 모두 출력하기
        # sql 실행
        # sql = f"""SELECT * FROM skyscrapers, bldg_images
        #           WHERE skyscrapers.id=1 AND skyscrapers.id = bldg_images.bldg_id"""
        sql = "SELECT * FROM skyscrapers"
        cursor.execute(sql)
        result = cursor.fetchall()
        result_copy = result
        # print(result)

        sql = "SELECT * FROM bldg_weather"
        cursor.execute(sql)
        results_weather = cursor.fetchall()

	    # 지도 위도, 경도 얻기
        lat_long = [result[0]['x_coord'], result[0]['y_coord']]
        m = folium.Map(lat_long, zoom_start=2)
        for countmap in range(1, 100):
            # m = folium.Map(lat_long, zoom_start=12, tiles='Stamen Terrain')
            # folium 한글깨짐 해결 방법 : 아래 명령어 실행 후 서버 재실행
            # sudo pip3 install git+https://github.com/python-visualization/branca.git@master

            # text = "<b>#"+str(countmap)+" "+result[countmap]['building_name']+"</b></br><i>"+result[countmap]['city_name']+"</i></br>"\
            #        +"<div><a href='http://localhost:8000/buildings/detail/"+str(countmap)+"'>상세히보기</a></div>" 
            # 팝업창 내용 넣기
            text = "<b>#"+str(countmap)+" "+result[countmap]['building_name']+"</b></br><i>"+result[countmap]['city_name']+"</i>"
            weather = get_weather_skyscrapers(result[countmap]['id'], results_weather)
            if weather:
                text = text + "<br> main_weather : </b>" + weather['main_weather']
                text = text + "<br> temperature : </b>" + weather['temperature_C']
                text = text + "<br> humidity : </b>" + weather['humidity']
            lat_long = [result[countmap]['x_coord'], result[countmap]['y_coord']]
            popText = folium.Html(text+str(lat_long), script=True)
            popup = folium.Popup(popText, max_width=2650)
            folium.CircleMarker(lat_long, radius=10, popup=popup, color='#3186cc',fill_color='#3186cc',).add_to(m)

        # folium HTML 얻기
        m = m._repr_html_() #updated

        # sql = "SELECT id, ranking, building_name, city_name, country, height_m FROM skyscrapers"
        # cursor.execute(sql)
        result = result_copy

        paginator = Paginator(result, 10)
        page_obj = paginator.get_page(page)

        # context = {'data':page_obj, 'bldg_map': m}

    # return render(request, 'home.html', context)
    # return render(request, 'home.html')
        context = {'bldg_data':page_obj, 'bldg_map': m}    
    return context

def home(request):
    context = skyscrapers_home(request)

    return render(request, 'home.html', context)

def maplist(request):
    context = skyscrapers_home(request)

    return render(request, 'buildings/bldg_maplist.html', context)



def bldg_list(request):
    page = request.GET.get('page', '1')

    # ranking', 'building_name', 'city_name', 'country', 'height_m', 'height_ft',
    # 'floor', 'completion_year', 'material', 'category', 'thumbnail',
    # 'x_coord', 'y_coord', 'reg_date'

    with connection.cursor() as cursor:
        sql = "SELECT id, ranking, building_name, city_name, country, height_m FROM skyscrapers"
        cursor.execute(sql)
        result = cursor.fetchall()
        paginator = Paginator(result, 10)
        page_obj = paginator.get_page(page)
        print(result)

        context = {'data':page_obj}

    return render(request, 'buildings/bldg_list.html', context)

def bldg_detail(request, id):
    with connection.cursor() as cursor:
        sql = f"""SELECT * FROM skyscrapers, bldg_images
                  WHERE skyscrapers.id={id} AND skyscrapers.id = bldg_images.bldg_id"""
        cursor.execute(sql)
        result = cursor.fetchall()
        print(result)

        lat_long = [result[0]['x_coord'], result[0]['y_coord']]
        m = folium.Map(lat_long, zoom_start=14)
        # m = folium.Map(lat_long, zoom_start=12, tiles='Stamen Terrain')

        # folium 한글깨짐 해결 방법 : 아래 명령어 실행 후 서버 재실행
        # sudo pip3 install git+https://github.com/python-visualization/branca.git@master
        text = "<b>"+result[0]['building_name']+"</b></br><i>"+result[0]['city_name']+"</i></br>"

        popText = folium.Html(text+str(lat_long), script=True)
        popup = folium.Popup(popText, max_width=2650)
        folium.Marker(location=lat_long, popup=popup).add_to(m)
        m=m._repr_html_() #updated

        context = {'data':result, 'bldg_map': m}

    return render(request, 'buildings/bldg_detail.html', context)

templates/buildings/bldg_detail.html
<!DOCTYPE html>
<html>
<title>Map & Info</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- // skyscraper start // -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Document</title>

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
 <!-- // skyscraper end // -->

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">

<style>
.gallery {
-webkit-column-count: 3;
-moz-column-count: 3;
column-count: 3;
-webkit-column-width: 33%;
-moz-column-width: 33%;
column-width: 33%; }
.gallery .pics {
-webkit-transition: all 350ms ease;
transition: all 350ms ease; }
.gallery .animation {
-webkit-transform: scale(1);
-ms-transform: scale(1);
transform: scale(1); }

@media (max-width: 450px) {
.gallery {
-webkit-column-count: 1;
-moz-column-count: 1;
column-count: 1;
-webkit-column-width: 100%;
-moz-column-width: 100%;
column-width: 100%;
}
}

@media (max-width: 400px) {
.btn.filter {
padding-left: 1.1rem;
padding-right: 1.1rem;
}
}

body,h1,h2{font-family: "Raleway", sans-serif}
body, html {height: 100%}
p {line-height: 2}
.bgimg, .bgimg2 {
  min-height: 100%;
  background-position: center;
  background-size: cover;
}
.bgimg {background-image: url("/static/css/bldg03.jpg")}
.bgimg2 {background-image: url("/static/css/mountain05.jpg")}

tr.detail {
display: none;
width: 100%;
}
tr.detail div {
display: none;
}
.showmore:hover {
cursor: pointer;
}
.spacing{
    letter-spacing:7px;
}
.spacing1{
    letter-spacing:3px;
}
</style>
<body>

<!-- Navbar (sticky bottom) -->
<div class="w3-bottom w3-hide-small">
  <div class="w3-bar w3-white w3-center w3-padding w3-opacity-min w3-hover-opacity-off">
    <a href="/#home" style="width:25%" class="w3-bar-item w3-button">Home</a>
    <a href="/mountains/" style="width:25%" class="w3-bar-item w3-button">MOUNTAINS</a>
    <a href="/buildings/" style="width:25%" class="w3-bar-item w3-button">SKYSCRAPERS</a>
    <a href="/#rsvp" style="width:25%" class="w3-bar-item w3-button w3-hover-black">MEMBER</a>
  </div>
</div>

<div class="w3-container w3-padding-64 w3-light-grey w3-grayscale-min w3-center" id="skyscraper">
  <div class="w3-content">
    <h1 class="w3-text-grey w3-xlarge spacing">SKYSCRAPERS DETAIL</h1><br>
    
  </div>
    <div class="container">
    <div class="w3-container">  
    <div class="w3-row-padding" style="margin:10 -16px" id="bldg_detail">
        <br>
        <table class="table table-hover " >
            <tbody>
                <tr> 
                    <td class="spacing1">RANK</td>
                    <td class="spacing1">{{data.0.ranking}}</td>
                </tr>
                <tr>
                    <td class="spacing1">BUILDING NAME</td>
                    <td class="spacing1">{{data.0.building_name}}</td>
                </tr>
                <tr>
                    <td class="spacing1">CITY NAME</td>
                    <td class="spacing1">{{data.0.city_name}}</td>
                </tr>
                <tr>
                    <td class="spacing1">COUNTRY</td>
                    <td class="spacing1">{{data.0.country}}</td>
                </tr>
                <tr>
                    <td class="spacing1">HEIGHT(m)</td>
                    <td class="spacing1">{{data.0.height_m}}</td>
                </tr>
                <tr>
                    <td class="spacing1">HEIGHT(ft)</td>
                    <td class="spacing1">{{data.0.height_ft}}</td>
                </tr>
                <tr>
                    <td class="spacing1">FLOOR</td>
                    <td class="spacing1">{{data.0.floor}}</td>
                </tr>
                <tr>
                    <td class="spacing1">COMPLETION YEAR</td>
                    <td class="spacing1">{{data.0.completion_year}}</td>
                </tr>
                <tr>
                    <td class="spacing1">MATERIAL</td>
                    <td class="spacing1">{{data.0.material}}</td>
                </tr>
                <tr>
                    <td class="spacing1">CATEGORY</td>
                    <td class="spacing1">{{data.0.category}}</td>
                </tr>
                <tr>
                    <td class="spacing1">COORDINATE(X)</td>
                    <td class="spacing1">{{data.0.x_coord}}</td>
                </tr>
                <tr>
                    <td class="spacing1">COORDINATE(Y)</td>
                    <td class="spacing1">{{data.0.y_coord}}</td>
                </tr>
                <tr>
                    <td class="spacing1">REGISTERD DATE</td>
                    <td class="spacing1">{{data.0.reg_date}}</td>
                </tr>
                </tr>
            </tbody>
        </table>
    <div class="gallery" id="gallery">
    {% for row in data %}
        <div class="mb-3 pics animation all 1">
        <img class="img-fluid" src="https://{{row.bldg_link}}" alt="Card image cap">
        </div>
    {% endfor %}
    </div>

    {{ bldg_map|safe }}
    </div>
    </div>
    </div>
</div>

</body>
</html>

templates/buildings/bldg_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<style>
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 8px;
  text-align: left;
  border-bottom: 1px solid #ddd;
}

tr:hover {background-color:#f5f5f5;}
</style>
<body>

{% csrf_token %}
    <div class="container">
        <table class="table">
            <thead>
            </thead>
            <tbody>
                {% for row in data %}
                <tr>
                    <td><a href="{% url 'buildings:bldg_detail' row.id %}">{{row.id}}</a></td>
                    <td><a href="{% url 'buildings:bldg_detail' row.id %}">{{row.ranking}}</a></td>
                    <td><a href="{% url 'buildings:bldg_detail' row.id %}">{{row.building_name}}</a></td>
                    <td><a href="{% url 'buildings:bldg_detail' row.id %}">{{row.city_name}}({{row.country}})</a></td>
                    <td><a href="{% url 'buildings:bldg_detail' row.id %}">{{row.height_m}} {{"m"}}</a></td>
                    <td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if data.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ data.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in data.paginator.page_range %}
                {% if page_number == data.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if data.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ data.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
    </div>

</body>
</html>

templates/buildings/bldg_maplist.html
<!DOCTYPE html>
<html>
<title>Map & Info</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- // skyscraper start // -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Document</title>

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
 <!-- // skyscraper end // -->

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">

<style>
body,h1,h2{font-family: "Raleway", sans-serif}
body, html {height: 100%}
p {line-height: 2}
.bgimg, .bgimg2 {
  min-height: 100%;
  background-position: center;
  background-size: cover;
}
.bgimg {background-image: url("/static/css/bldg03.jpg")}
.bgimg2 {background-image: url("/static/css/mountain05.jpg")}

tr.detail {
display: none;
width: 100%;
}
tr.detail div {
display: none;
}
.showmore:hover {
cursor: pointer;
}
.spacing{
    letter-spacing:7px;
}
.spacing1{
    letter-spacing:4px;
}
.press {
    color: #333;
    font-size: 5em;
    text-shadow: 0 1px 0 #777, 0 -1px 0 #000;
}

</style>
<body>


<!-- Navbar (sticky bottom) -->
<div class="w3-bottom w3-hide-small">
  <div class="w3-bar w3-blue-gray w3-center w3-padding w3-opacity-min w3-hover-opacity-off">
    <a href="/#home" style="width:25%" class="w3-bar-item w3-button">HOME</a>
    <a href="/mountains/" style="width:25%" class="w3-bar-item w3-button">MOUNTAINS</a>
    <a href="/buildings/" style="width:25%" class="w3-bar-item w3-button">SKYSCRAPERS</a>
    <a href="/#rsvp" style="width:25%" class="w3-bar-item w3-button w3-hover-black">MEMBER</a>
  </div>
</div>

<!-- skyscrapers information -->

<div class="w3-container w3-padding-64 w3-light-gray w3-grayscale-min w3-center" id="skyscraper">
  <div class="w3-content">
    <h1 class="w3-text-grey w3-xlarge spacing1">S K Y S C R A P E R S</h1>
    <p class="w3-text-gray spacing1">100 Tallest Buildings in the World</p>
</div>


<!-- skyscraper list -->
  <div class="container">
  <div class="w3-container">  
  <div class="w3-row-padding" style="margin:10 -16px" id="bldg_list">
  <br>
  {{ bldg_map|safe }} 
        <!-- // skyscraper list start // -->
        <table class="table" id="table_bldg_list">
            <thead>
                <tr>
                    <th class="spacing">RANK</th>
                    <th class="spacing">BUILDING NAME</th>
                    <th class="spacing">CITY</th>
                    <th class="spacing">HEIGHT (m)</th>
                </tr>
            </thead>
            <tbody>
                {% for row in bldg_data %}
                <tr>
                    <td><a href="{% url 'buildings:bldg_detail' row.id %}">{{row.ranking}}</a></td>
                    <td><a href="{% url 'buildings:bldg_detail' row.id %}">{{row.building_name}}</a></td>
                    <td><a href="{% url 'buildings:bldg_detail' row.id %}">{{row.city_name}}({{row.country}})</a></td>
                    <td><a href="{% url 'buildings:bldg_detail' row.id %}">{{row.height_m}} {{"m"}}</a></td>
                    <td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if bldg_data.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ bldg_data.previous_page_number }}#table_bldg_list">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in bldg_data.paginator.page_range %}
                {% if page_number == bldg_data.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}#table_bldg_list">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}#table_bldg_list">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if bldg_data.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ bldg_data.next_page_number }}#table_bldg_list">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
  </div>
  </div>
  </div>
        <!-- // skyscraper list end // -->
</div>
<!-- End MT photo -->


</body>
</html>