buildings/urls.py
from django.contrib import admin
from django.urls import path

from buildings import views

app_name = 'buildings'

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('list', views.bldg_list, name='bldg_list'),
    path('detail/<int:id>/', views.bldg_detail, name='bldg_detail'),
    path('', views.maplist, name='maplist'),
]

mountains/urls.py
from django.contrib import admin
from django.urls import path

from mountains import views

app_name = 'mountains'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('list', views.mt_list, name='mt_list'),
    path('detail/<int:id>/', views.mt_detail, name='mt_detail'),
    # path('', views.mt_map, name='mt_map'),
    path('listajax/', views.listajax, name='listajax'),
    path('listajax/detail/', views.listajax_detail, name='listajax_detail'),
    path('', views.maplist, name='maplist'),
]

web_config/urls.py
from django.urls import path, include

"""web_config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from buildings import views as bldgviews

urlpatterns = [
    path('', bldgviews.home, name="home"),
    path('admin/', admin.site.urls),
    path('mountains/', include('mountains.urls')),
    path('buildings/', include('buildings.urls')),
]

mountains/models.py
from django.db import models

# Create your models here.

mountains/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator
import pymysql.cursors
import folium
from django.http import JsonResponse

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='1234',
                             db='mydb',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

# Create your views here.
def mt_list(request):
    page = request.GET.get('page', '1')

    with connection.cursor() as cursor:
        sql = "SELECT id, name, title, height FROM mountains"
        cursor.execute(sql)
        result = cursor.fetchall()
        paginator = Paginator(result, 10)
        page_obj = paginator.get_page(page)
        # print(result)

        context = {'data':page_obj}

    return render(request, 'mountains/mt_list.html', context)

def mt_detail(request, id):
    with connection.cursor() as cursor:
        sql = f"""SELECT * FROM mountains, mt_images
                  WHERE mountains.id={id} AND mountains.id = mt_images.mt_id"""
        cursor.execute(sql)
        result = cursor.fetchall()
        print(result)

        lat_long = [result[0]['y_coord'], result[0]['x_coord']]
        m = folium.Map(lat_long, zoom_start=1)
        # m = folium.Map(lat_long, zoom_start=12, tiles='Stamen Terrain')

        # folium 한글깨짐 해결 방법 : 아래 명령어 실행 후 서버 재실행
        # sudo pip3 install git+https://github.com/python-visualization/branca.git@master
        text = "<b>"+result[0]['name']+"</b></br><i>"+result[0]['title']+"</i></br>"

        popText = folium.Html(text+str(lat_long), script=True)
        popup = folium.Popup(popText, max_width=2650)
        folium.Marker(location=lat_long, popup=popup).add_to(m)
        m = m._repr_html_() #updated

        context = {'data':result, 'mountain_map': m}

    return render(request, 'mountains/mt_detail.html', context)


def mt_map(request):

    page = request.GET.get('page', '1')

    with connection.cursor() as cursor:
        sql = "SELECT * FROM mountains"
        cursor.execute(sql)
        results = cursor.fetchall()
        # print(results)
        paginator = Paginator(results, 10)
        page_obj = paginator.get_page(page)

        # folium
        m = folium.Map([35.95, 128.00], zoom_start=7)       # 우리나라 중심 좌표 : [35.95, 128.25]

        for result in results:
            lat_long = [result['y_coord'], result['x_coord']]
            # print(lat_long)
            # m = folium.Map(lat_long, zoom_start=12, tiles='Stamen Terrain')

            # folium 한글깨짐 해결 방법 : 아래 명령어 실행 후 서버 재실행
            # sudo pip3 install git+https://github.com/python-visualization/branca.git@master
            text = "<b>"+result['name']+"</b><br><i>"\
                        +result['title']+"</i><br>"\
                        +result['y_coord']+"<br>"\
                        +result['x_coord']+"<br>"

            popText = folium.Html(text, script=True)
            popup = folium.Popup(popText, max_width=150)
            folium.RegularPolygonMarker(location=lat_long,
                                        popup=popup,
                                        number_of_sides=3,
                                        rotation=30,
                                        radius=7).add_to(m)

        m = m._repr_html_() #updated

        context = {'data':page_obj, 'mountain_map': m}
        # context = {'mountain_map': m}

    return render(request, 'mountains/mt_map.html', context)


def listajax(request):

    with connection.cursor() as cursor:
        sql = "SELECT * FROM mountains"
        cursor.execute(sql)
        results = cursor.fetchall()

        #number of items on each page
        number_of_item = 10
        #Paginator
        paginator = Paginator(results, number_of_item)
        #query_set for first page
        first_page = paginator.page(1)
        #range of page ex range(1, 3)
        page_range = paginator.page_range


        # folium
        m = folium.Map([35.95, 128.00], zoom_start=7)       # 우리나라 중심 좌표 : [35.95, 128.25]

        for result in results:
            lat_long = [result['y_coord'], result['x_coord']]
            # print(lat_long)
            # m = folium.Map(lat_long, zoom_start=12, tiles='Stamen Terrain')

            # folium 한글깨짐 해결 방법 : 아래 명령어 실행 후 서버 재실행
            # sudo pip3 install git+https://github.com/python-visualization/branca.git@master
            text = "<b>"+result['name']+"</b><br><i>"\
                        +result['title']+"</i><br>"\
                        +result['y_coord']+"<br>"\
                        +result['x_coord']+"<br>"

            popText = folium.Html(text, script=True)
            popup = folium.Popup(popText, max_width=150)
            folium.RegularPolygonMarker(location=lat_long,
                                        popup=popup,
                                        number_of_sides=3,
                                        rotation=30,
                                        radius=7).add_to(m)

        m = m._repr_html_() #updated

        context = {
        'paginator':paginator,
        'first_page':first_page,
        'page_range':page_range,
        'mountain_map':m
        }

        if request.method == 'POST':
            page_n = request.POST.get('page_n', None) #getting page number
            # results = list(paginator.page(page_n))
            results = list(paginator.page(page_n))
            return JsonResponse({"results":results})



    return render(request, 'mountains/mt_map_ajax.html', context)


def listajax_detail(request):
    if request.method == 'POST':
        id = request.POST.get('id', 1)

        with connection.cursor() as cursor:
            sql = f"""SELECT * FROM mountains, mt_images
                    WHERE mountains.id={id} AND mountains.id = mt_images.mt_id"""
            cursor.execute(sql)
            results = cursor.fetchall()
            print(results)

            lat_long = [results[0]['y_coord'], results[0]['x_coord']]
            m = folium.Map(lat_long, zoom_start=14)
            # m = folium.Map(lat_long, zoom_start=12, tiles='Stamen Terrain')

            # folium 한글깨짐 해결 방법 : 아래 명령어 실행 후 서버 재실행
            # sudo pip3 install git+https://github.com/python-visualization/branca.git@master
            text = "<b>"+results[0]['name']+"</b></br><i>"+results[0]['title']+"</i></br>"

            popText = folium.Html(text+str(lat_long), script=True)
            popup = folium.Popup(popText, max_width=2650)
            folium.Marker(location=lat_long, popup=popup).add_to(m)
            m = m._repr_html_() #updated

        #     context = {'data':result, 'mountain_map': m}
        #     results = list(paginator.page(page_n))
        # return render(request, 'mountains/mt_detail.html', context)

    return JsonResponse({"results":list(results), 'mountain_map':m})


def maplist(request):
    page = request.GET.get('page', '1')

    with connection.cursor() as cursor:
        sql = "SELECT * FROM mountains, mt_weather WHERE mountains.id = mt_weather.mt_id"
        cursor.execute(sql)
        results = cursor.fetchall()

        number_of_item = 10
        paginator = Paginator(results, number_of_item)
        page_range = paginator.page_range
        page_obj = paginator.get_page(page)


        # folium
        m = folium.Map([35.95, 128.00], zoom_start=7)       # 우리나라 중심 좌표 : [35.95, 128.25]

        for result in results:
            lat_long = [result['y_coord'], result['x_coord']]

            # folium 한글깨짐 해결 방법 : 아래 명령어 실행 후 서버 재실행
            # sudo pip3 install git+https://github.com/python-visualization/branca.git@master
            text = "<b>"+result['name']+"</b></br><i>기온 : "+result['temp']+" °C</i></br>"\
                   "<i>기압 : "+result['pressure']+" hpa</i></br><i>습도 : "+result['humidity']+" %</i></br>"\
                   "<i>풍속 : "+result['wind_speed']+" Knots</i></br><i>구름량 : "+result['clouds']+"</i></br>"\

            popText = folium.Html(text, script=True)
            popup = folium.Popup(popText, max_width=150)
            folium.RegularPolygonMarker(location=lat_long,
                                        popup=popup,
                                        number_of_sides=3,
                                        rotation=30,
                                        radius=7).add_to(m)

        m = m._repr_html_()

        links, maps = [], []
        for id in page_range:
            sql = f"""SELECT * FROM mountains, mt_images
                      WHERE mountains.id={id} AND mountains.id = mt_images.mt_id"""
            cursor.execute(sql)
            results = cursor.fetchall()

            l = [r['link'] for r in results]
            links.append(l)

            lat_long = [results[0]['y_coord'], results[0]['x_coord']]
            m_detail = folium.Map(lat_long, zoom_start=14)
            # m_detail = folium.Map(lat_long, zoom_start=12, tiles='Stamen Terrain')

            # folium 한글깨짐 해결 방법 : 아래 명령어 실행 후 서버 재실행
            # sudo pip3 install git+https://github.com/python-visualization/branca.git@master
            text = "<b>"+results[0]['name']+"</b><br><i>"\
                        +results[0]['title']+"</i><br>"\
                        +results[0]['y_coord']+"<br>"\
                        +results[0]['x_coord']+"<br>"

            popText = folium.Html(text+str(lat_long), script=True)
            popup = folium.Popup(popText, max_width=2650)
            folium.Marker(location=lat_long, popup=popup).add_to(m_detail)
            m_detail = m_detail._repr_html_() #updated
            maps.append(m_detail)

        data = [d for d in zip(page_obj, links, maps)]

        context = {'data':data, 'paging':page_obj, 'mountain_map': m}

    return render(request, 'mountains/mt_maplist.html', context)

templates/mountains/design_template.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<style>
body,h1,h2{font-family: "Raleway", sans-serif}
body, html {height: 100%}
p {line-height: 2}
.bgimg, .bgimg2 {
  min-height: 100%;
  background-position: center;
  background-size: cover;
}
.bgimg {background-image: url("/w3images/wedding_couple.jpg")}
.bgimg2 {background-image: url("/w3images/flowers.jpg")}
</style>
<body>

<!-- Header / Home-->
<header class="w3-display-container w3-wide bgimg w3-grayscale-min" id="home">
  <div class="w3-display-middle w3-text-white w3-center">
    <h1 class="w3-jumbo">Jane & John</h1>
    <h2>Are getting married</h2>
    <h2><b>17.07.2017</b></h2>
  </div>
</header>

<!-- Navbar (sticky bottom) -->
<div class="w3-bottom w3-hide-small">
  <div class="w3-bar w3-white w3-center w3-padding w3-opacity-min w3-hover-opacity-off">
    <a href="#home" style="width:25%" class="w3-bar-item w3-button">Home</a>
    <a href="#us" style="width:25%" class="w3-bar-item w3-button">Jane & John</a>
    <a href="#wedding" style="width:25%" class="w3-bar-item w3-button">Wedding</a>
    <a href="#rsvp" style="width:25%" class="w3-bar-item w3-button w3-hover-black">RSVP</a>
  </div>
</div>

<!-- About / Jane And John -->
<div class="w3-container w3-padding-64 w3-pale-red w3-grayscale-min" id="us">
  <div class="w3-content">
    <h1 class="w3-center w3-text-grey"><b>Jane & John</b></h1>
    <img class="w3-round w3-grayscale-min" src="/w3images/wedding_couple2.jpg" style="width:100%;margin:32px 0">
    <p><i>You all know us. And we all know you. We are getting married lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint
      occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
      laboris nisi ut aliquip ex ea commodo consequat.</i>
    </p><br>
    <p class="w3-center"><a href="#wedding" class="w3-button w3-black w3-round w3-padding-large w3-large">Wedding Details</a></p>
  </div>
</div>

<!-- Background photo -->
<div class="w3-display-container bgimg2">
  <div class="w3-display-middle w3-text-white w3-center">
    <h1 class="w3-jumbo">You Are Invited</h1><br>
    <h2>Of course..</h2>
  </div>
</div>

<!-- Wedding information -->
<div class="w3-container w3-padding-64 w3-pale-red w3-grayscale-min w3-center" id="wedding">
  <div class="w3-content">
    <h1 class="w3-text-grey"><b>THE WEDDING</b></h1>
    <img class="w3-round-large w3-grayscale-min" src="/w3images/wedding_location.jpg" style="width:100%;margin:64px 0">
    <div class="w3-row">
      <div class="w3-half">
        <h2>When</h2>
        <p>Wedding Ceremony - 2:00pm</p>
        <p>Reception & Dinner - 5:00pm</p>
      </div>
      <div class="w3-half">
        <h2>Where</h2>
        <p>Some place, an address</p>
        <p>Some where, some address</p>
      </div>
    </div>
  </div>
</div>

<!-- RSVP section -->
<div class="w3-container w3-padding-64 w3-pale-red w3-center w3-wide" id="rsvp">
  <h1>HOPE YOU CAN MAKE IT!</h1>
  <p class="w3-large">Kindly Respond By January, 2017</p>
  <p class="w3-xlarge">
    <button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-round w3-red w3-opacity w3-hover-opacity-off" style="padding:8px 60px">RSVP</button>
  </p>
</div>

<!-- RSVP modal -->
<div id="id01" class="w3-modal">
  <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="padding:32px;max-width:600px">
    <div class="w3-container w3-white w3-center">
      <h1 class="w3-wide">CAN YOU COME?</h1>
      <p>We really hope you can make it.</p>
      <form>
        <input class="w3-input w3-border" type="text" placeholder="Name(s)" name="name">
      </form>
      <p><i>Sincerely, John & Jane</i></p>
      <div class="w3-row">
        <div class="w3-half">
          <button onclick="document.getElementById('id01').style.display='none'" type="button" class="w3-button w3-block w3-green">Going</button>
        </div>
        <div class="w3-half">
          <button onclick="document.getElementById('id01').style.display='none'" type="button" class="w3-button w3-block w3-red">Can't come</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="w3-center w3-black w3-padding-16">
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-text-green">w3.css</a></p>
</footer>
<div class="w3-hide-small" style="margin-bottom:32px"> </div>

</body>
</html>

templates/mountains/index.html
<html>
    <head>
        <title>How to make a pagination with django and jquery</title>
        <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
    </head>
    <body>

<!-- queryset for first page -->
<div id="posts">
    {% for i in first_page %}
    <h2>{{i.name}}</h2>
    {% endfor %}
</div>


<!-- loop pagination -->
{% for i in page_range %}
<a style="margin-left: 5px; font-size: 20px;" href="{{i}}">{{i}}</a>
{% endfor %}


<script>
$('a').click(function(event){
    event.preventDefault();
    var page_n = $(this).attr('href');
    // ajax
        $.ajax({
                type: "POST",
                url: "{% url 'mountains:listajax' %}", // name of url
                data : {
                page_n : page_n, //page_number
                csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function (resp) {
                //loop
                $('#posts').html('')
               $.each(resp.results, function(i, val) {
                 //apending posts
                $('#posts').append('<h2>' + val.name + '</h2>')
               });
            },
            error: function () {}
        }); //

});
</script>



    </body></html>

templates/mountains/mt_list.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1 {font-family: "Montserrat", sans-serif}
img {margin-bottom: -7px}
.w3-row-padding img {margin-bottom: 12px}
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  padding: 8px;
  text-align: left;
  border-bottom: 1px solid #ddd;
}

tr:hover {background-color:#f5f5f5;}
</style>
<body>

    <!-- Header -->
    <div class="w3-opacity">
    <div class="w3-clear"></div>
    <header class="w3-center w3-margin-bottom">
    <h1><b>INFORMATION</b></h1>
    <p><b> </b></p>
    <br><br>
    </header>
    </div>
    
    <div class="container">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>NAME</th>
                    <th>TITLE</th>
                    <th>HEIGHT</th>
                </tr>
            </thead>
            <tbody>
                {% for row in data %}
                <tr>
                    <td><a href="{% url 'mountains:mt_detail' row.id %}">{{row.id}}</a></td>
                    <td><a href="{% url 'mountains:mt_detail' row.id %}">{{row.name}}</a></td>
                    <td><a href="{% url 'mountains:mt_detail' row.id %}">{{row.title}}</a></td>
                    <td><a href="{% url 'mountains:mt_detail' row.id %}">{{row.height}}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if data.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ data.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in data.paginator.page_range %}
                {% if page_number == data.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if data.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ data.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
    </div>

</body>
</html>

templates/mountains/mt_map_ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

    <style type="text/css">
        tr.detail {
        display: none;
        width: 100%;
        }
        tr.detail div {
        display: none;
        }
        .showmore:hover {
        cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">

        {{ mountain_map|safe }}

    </div>

    <div class="container">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>title</th>
                    <th>height</th>
                </tr>
            </thead>
            <tbody id="posts">
                {% for i in first_page %}
                    <tr>
                        <td>{{i.id}}</td>
                        <td>{{i.name}}</td>
                        <td>{{i.title}}</td>
                        <td>{{i.height}}</td>
                        <td><button class="showmore" value={{i.id}}>more</button></td>
                    </tr>
                    <tr class="detail">

                    </tr>
                {% endfor %}
            </tbody>
        </table>


        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if data.has_previous %}
            <li class="page-item">
                <a class="page-link" href="data.previous_page_number">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in page_range %}
                {% if page_number == data.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="{{page_number}}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{page_number}}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if data.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{data.next_page_number}}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
    </div>




<script>
    $('a').click(function(event){
        event.preventDefault();
        var page_n = $(this).attr('href');
        // ajax
            $.ajax({
                    type: "POST",
                    url: "{% url 'mountains:listajax' %}", // name of url
                    data:{
                        page_n : page_n, //page_number
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function (jsonObj) {
                        console.log(jsonObj)
                        $('#posts').html('');
                        $('tr').each(function(i, val) {
                            for (var data of jsonObj['results']) {
                                console.log(data['name'])
                                //loop
                                //apending posts
                                var txt = '<tr><td>'+data['id']+'</td><td>'+data['name']+'</td><td>'+data['title']+'</td><td>'+data['height']+'</td></tr>'
                                $('#posts').append(txt);
                            };
                        });
                    },
                    error: function () {}
            });
    });

    // table sliding toggle
    $(function() {
        $('button.showmore').click(function(e) {
            e.preventDefault();

            // We break and store the result so we can use it to hide
            // the row after the slideToggle is closed
            var targetrow = $(this).closest('tr').next('.detail');
            var id = $(this).attr('value');
                $.ajax({
                        type: "POST",
                        url: "{% url 'mountains:listajax_detail' %}", // name of url
                        data:{
                            id : id,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        },
                        success: function (jsonObj) {
                            targetrow.append('');
                            data = jsonObj['results'][0]
                            var txt0 = "<td colspan='3'><div><table class='table table-striped'><tbody>"
                            var txt1 = "<tr><td>id</td><td>"+data['id']+"</td></tr><tr><td>name</td><td>"+data['name']
                            var txt2 = "</td></tr><tr><td>title</td><td>"+data['title']+"</td></tr><tr><td>site</td><td>"+data['site']
                            var txt3 = "</td></tr><tr><td>height</td><td>"+data['height']+"</td></tr><tr><td>feature</td><td>"+data['feature']
                            var txt4 = "</td></tr><tr><td>overview</td><td>"+data['overview']+"</td></tr><tr><td>information</td><td>"+data['information']
                            var txt5 = "</td></tr><tr><td>leadtime</td><td>"+data['leadtime']+"</td></tr><tr><td>x_coord</td><td>"+data['x_coord']
                            var txt6 = "</td></tr><tr><td>y_coord</td><td>"+data['y_coord']+"</td></tr>"
                            var txt = txt0 + txt1 + txt2 + txt3 + txt4 + txt5 + txt6
                            targetrow.append(txt);

                            targetrow.show().find('div').slideToggle('fast', function(){
                                if (!$(this).is(':visible')) {
                                    targetrow.hide();
                                }
                            });
                        },
                        error: function () {}
                });


        });
    });


</script>


</body>
</html>


<script>
$(function() {
  $('a.showmore').click(function(e) {
    e.preventDefault();
    // We break and store the result so we can use it to hide
    // the row after the slideToggle is closed
    var targetrow = $(this).closest('tr').next('.detail');
    targetrow.show().find('div').slideToggle('slow', function(){
      if (!$(this).is(':visible')) {
        targetrow.hide();
      }
    });
  });
});
</script>